export default function Footer() {
  return (
    <footer className="py-10 px-4 border-t border-border/50">
      <div className="max-w-4xl mx-auto text-center text-sm text-muted">
        <p className="mb-2">
          Built with{" "}
          <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer" className="text-rose-400 hover:underline">
            Next.js
          </a>
          ,{" "}
          <a href="https://tailwindcss.com" target="_blank" rel="noopener noreferrer" className="text-rose-400 hover:underline">
            Tailwind CSS
          </a>
          , and{" "}
          <a href="https://framermotion.framer.website" target="_blank" rel="noopener noreferrer" className="text-rose-400 hover:underline">
            Framer Motion
          </a>
        </p>
        <p className="mb-2">
          Figures generated by{" "}
          <a href="https://numpy.org" target="_blank" rel="noopener noreferrer" className="text-rose-400 hover:underline">
            NumPy
          </a>{" "}
          +{" "}
          <a href="https://scipy.org" target="_blank" rel="noopener noreferrer" className="text-rose-400 hover:underline">
            SciPy
          </a>{" "}
          +{" "}
          <a href="https://matplotlib.org" target="_blank" rel="noopener noreferrer" className="text-rose-400 hover:underline">
            Matplotlib
          </a>
        </p>
        <p>
          <a
            href="https://github.com/AyushDocs/lindblad-solver"
            target="_blank"
            rel="noopener noreferrer"
            className="text-rose-400 hover:underline"
          >
            GitHub
          </a>{" "}
          &middot;{" "}
          <span>Open Quantum Systems &mdash; 2025</span>
        </p>
      </div>
    </footer>
  );
}
